<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc-reply message-id="m-6" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<rpc-error>
<error-type>application</error-type>
<error-tag>operation-failed</error-tag>
<error-severity>error</error-severity>
<error-message>Transaction commit failed on canCommit encountered an unexpected failure 2 Cause: Metadata not available for modification NodeModification [identifier=(urn:opendaylight:params:xml:ns:yang:v3po?revision=2015-01-05)bridge-domain, modificationType=TOUCH, childModification={(urn:opendaylight:params:xml:ns:yang:v3po?revision=2015-01-05)bridge-domain[{(urn:opendaylight:params:xml:ns:yang:v3po?revision=2015-01-05)name=testBD2}]=NodeModification [identifier=(urn:opendaylight:params:xml:ns:yang:v3po?revision=2015-01-05)bridge-domain[{(urn:opendaylight:params:xml:ns:yang:v3po?revision=2015-01-05)name=testBD2}], modificationType=WRITE, childModification={}]}]</error-message>
</rpc-error>
</rpc-reply>
