#!/bin/bash
echo "Downloading yang dependencies..."

DIRECTORY="odl-lispflowmapping-yang-files"

# odl-lispflowmapping-yang-files will contain all the yang files
# odl-lispflowmapping-yang-files/LispFlowMappingYANGBindings will
# contain all the binding files generated by pyangbind.
mkdir -p ${WORKSPACE}/$DIRECTORY

GITWEB_LISP="https://git.opendaylight.org/gerrit/gitweb?p=lispflowmapping.git;a=blob_plain"
GITWEB_MDSAL="https://git.opendaylight.org/gerrit/gitweb?p=mdsal.git;a=blob_plain"
GITWEB_CONTROLLER="https://git.opendaylight.org/gerrit/gitweb?p=controller.git;a=blob_plain"

# Download yang-files in the VM on fly using curl before generating
# binding files.
curl "$GITWEB_LISP;f=mappingservice/lisp-proto/src/main/yang/ietf-lisp-address-types.yang" -o ${WORKSPACE}/$DIRECTORY/ietf-lisp-address-types.yang
curl "$GITWEB_LISP;f=mappingservice/lisp-proto/src/main/yang/odl-lisp-proto.yang" -o ${WORKSPACE}/$DIRECTORY/odl-lisp-proto.yang
curl "$GITWEB_LISP;f=mappingservice/lisp-proto/src/main/yang/odl-inet-binary-types.yang" -o ${WORKSPACE}/$DIRECTORY/odl-inet-binary-types.yang
curl "$GITWEB_LISP;f=mappingservice/api/src/main/yang/odl-mappingservice.yang" -o ${WORKSPACE}/$DIRECTORY/odl-mappingservice.yang
curl "$GITWEB_LISP;f=mappingservice/lisp-proto/src/main/yang/odl-lisp-address-types.yang" -o ${WORKSPACE}/$DIRECTORY/odl-lisp-address-types.yang
curl "$GITWEB_MDSAL;f=model/ietf/ietf-yang-types/src/main/yang/ietf-yang-types.yang" -o ${WORKSPACE}/$DIRECTORY/ietf-yang-types.yang
curl "$GITWEB_MDSAL;f=model/ietf/ietf-inet-types/src/main/yang/ietf-inet-types.yang" -o ${WORKSPACE}/$DIRECTORY/ietf-inet-types.yang
curl "$GITWEB_MDSAL;f=model/yang-ext/src/main/yang/yang-ext.yang" -o ${WORKSPACE}/$DIRECTORY/yang-ext.yang
curl "$GITWEB_CONTROLLER;f=opendaylight/config/config-api/src/main/yang/config.yang" -o ${WORKSPACE}/$DIRECTORY/config.yang

# Go to odl-lispflowmapping-yang-files directory
cd ${WORKSPACE}/$DIRECTORY

# Currently bits are not supported in pyangbind plugin so
# We need to apply patch to generate pyangbind bindings
# Successfully.
curl https://raw.githubusercontent.com/ashishk1994/ODL_TEST/master/bits.patch -o bits.patch
patch -i bits.patch && echo 'Patch applied successfully!'

# Generate binding files using pyangbind
PYBINDPLUGIN=`/usr/bin/env python -c 'import pyangbind; import os; print "%s/plugin" % os.path.dirname(pyangbind.__file__)'`
pyang --plugindir $PYBINDPLUGIN -f pybind --build-rpcs --split-class-dir ${WORKSPACE}/$DIRECTORY/LISPFlowMappingYANGBindings ./odl-mappingservice.yang

# Go back the main direcory
cd ../../

echo "Yang Dependencies and bindings downloaded successfully in ${WORKSPACE}/$DIRECTORY"
