CONFIG_API = '/restconf/config'
OS_COMPUTE_1_IP = '10.164.224.218' #Compute Node 1 IP
OS_COMPUTE_2_IP = '10.164.224.217'  #Compute node 2 + ODL IP
OS_CONTROL_NODE_IP = '10.164.224.48'
OS_USER = 'root'
DEVSTACK_SYSTEM_PASSWORD = 'admin123'
DEVSTACK_DEPLOY_PATH = '/opt/stack/devstack/'
# ODL system variables
ODL_SYSTEM_IP = '10.164.224.48'  # Override if ODL is not running locally to pybot
ODL_SYSTEM_1_IP = '10.164.224.48'
USER_HOME = '/root/'
DELAY_AFTER_VM_CREATION = 30
VAR_BASE = '/home/SF218_4_11_2017/test/csit/variables/bgpfunctional'
RESTCONFPORT = 8181
BGP_SHOW = "display-bgp-config"
BGP_DELETE_NEIGH_CMD = "configure-bgp -op delete-neighbor --ip "
BGP_STOP_SERVER_CMD = "exec configure-bgp -op stop-bgp-server"
BGP_CONFIG_CMD = "configure-bgp -op start-bgp-server --as-num 100 --router-id "
BGP_CONFIG_ADD_NEIGHBOR_CMD = "exec configure-bgp -op add-neighbor --ip "
