netopeer2-server:
  image: sysrepo/sysrepo-netopeer2:latest
  hostname: netopeer2
  command: sh -c "
      /root/init_configuration.sh &&
      exec netopeer2-server -d -v3"
  environment:
     - CALL_HOME_SERVER_IP=ODL_SYSTEM_IP
     - CALL_HOME_SSH_PORT=6666
     - CALL_HOME_TLS_PORT=4335
  volumes:
    - ./configuration-files:/root/configuration-files
    - ./init_configuration.sh:/root/init_configuration.sh
