*** Settings ***
Documentation       Basic Tests for Persistence Test APP.
...
...                 Copyright (c) 2015 Hewlett-Packard Development Company, L.P. and others. All rights reserved.

Library             SSHLibrary
Library             Collections
Library             ../../../libraries/UtilLibrary.py
Resource            ../../../libraries/KarafKeywords.robot
Resource            ../../../libraries/Utils.robot
Variables           ../../../variables/Variables.py

Suite Setup         Setup Persistence Test App Environment
Suite Teardown      Cleanup Persistence Test Database


*** Variables ***
${username}         user1
${password}         user1
${email_addr}       user1@example.com
${location1}        BUILDING_1_FIRST_FLOOR
${location2}        BUILDING_2_FIRST_FLOOR
${device1_name}     node1
${device1_ip}       10.1.1.10
${device2_name}     node2
${device2_ip}       10.1.1.20


*** Test Cases ***
Verify User Test App
    [Documentation]    Verify the User functionality of the Persistence Test App
    ...    This test case performs the following:
    ...    1. Create a user
    ...    2. Verify user is created and can be fetched
    ...    3. Verify user is created with correct user name and email address
    ...    4. Verify unknown user cannot be authenticated
    ...    5. Disable the user
    ...    6. Verify disabled user can be fetched
    [Tags]    persistence    testapp
    Issue Command On Karaf Console    user:sign-up ${username} ${password} ${email_addr}
    ${output}=    Issue Command On Karaf Console    user:get-enabled
    ${string}=    Extract String To Validate    ${output}    User{username=Username{value=    0
    Should Match    ${string}    ${username}
    ${string}=    Extract String To Validate    ${output}    email=Email{value=    2
    Should Match    ${string}    ${email_addr}
    ${unknown_user}=    Set Variable    random
    ${output}=    Issue Command On Karaf Console    user:sign-in ${unknown_user} ${password}
    Should Contain    ${output}    Error executing command:
    Issue Command On Karaf Console    user:disable ${username}
    ${output}=    Issue Command On Karaf Console    user:get-disabled
    ${user_dstate}=    Set Variable    isEnabled=false
    ${data}=    Find User State    ${output}
    Should Contain    ${data}    ${user_dstate}

Verify Network Device Test App
    [Documentation]    Verify the Network Device functionality of the Persistence Test App
    ...    This test case performs the following:
    ...    1. Add a device
    ...    2. Verify device can be discovered
    ...    3. Assign a name to the device
    ...    4. Verify device name
    ...    5. Configure a location
    ...    6. Verify device location
    [Tags]    persistence    testapp
    Issue Command On Karaf Console    networkdevice:discover ${device1_ip}
    ${output}=    Issue Command On Karaf Console    networkdevice:get-reachable
    ${string}=    Extract String To Validate    ${output}    ipAddress=IpAddress{value=    2
    Should Match    ${string}    ${device1_ip}
    ${device_id}=    Find Device Id    ${device1_ip}
    Issue Command On Karaf Console    networkdevice:set-friendly-name ${device_id} ${device1_name}
    ${data}=    Find Device Name    ${device1_ip}
    Should Match    ${data}    ${device1_name}
    Issue Command On Karaf Console    networkdevice:set-location ${device_id} ${location1}
    ${data}=    Find Device Location    ${device1_ip}    ${location1}
    Should Match    ${data}    ${location1}

Verify Data Persistency
    [Documentation]    Verify that the data that is generated by Persistence Test App can be persisted
    ...    This test case performs the following:
    ...    1. Create a user
    ...    2. Add a device and configure name and location
    ...    3. Restart the controller
    ...    4. Verify user name, email address and state are persisted
    ...    5. Verify device name and location are persisted
    [Tags]    persistence    testapp
    Issue Command On Karaf Console    user:sign-up ${username} ${password} ${email_addr}
    Issue Command On Karaf Console    networkdevice:discover ${device2_ip}
    ${device_id}=    Find Device Id    ${device2_ip}
    Issue Command On Karaf Console    networkdevice:set-location ${device_id} ${location2}
    Issue Command On Karaf Console    networkdevice:set-friendly-name ${device_id} ${device2_name}
    Stop One Or More Controllers    ${ODL_SYSTEM_IP}
    Wait Until Keyword Succeeds    60s    3s    Controller Down Check    ${ODL_SYSTEM_IP}
    Start One Or More Controllers    ${ODL_SYSTEM_IP}
    UtilLibrary.Wait For Controller Up    ${ODL_SYSTEM_IP}    ${RESTCONFPORT}
    ${output}=    Issue Command On Karaf Console    user:get-enabled
    ${string}=    Extract String To Validate    ${output}    User{username=Username{value=    0
    Should Match    ${string}    ${username}
    ${string}=    Extract String To Validate    ${output}    email=Email{value=    2
    Should Match    ${string}    ${email_addr}
    ${data}=    Find User State    ${output}
    ${user_estate}=    Set Variable    isEnabled=true
    Should Contain    ${data}    ${user_estate}
    ${data}=    Find Device Name    ${device2_ip}
    Should Match    ${data}    ${device2_name}
    ${data}=    Find Device Location    ${device2_ip}    ${location2}
    Should Match    ${data}    ${location2}


*** Keywords ***
Extract String To Validate
    [Documentation]    Take the output of a content, the string to be splitted and the
    ...    index of the data from the output, parse the strin and return the data that includes
    ...    user's name, user's email address, device's IP address
    [Arguments]    ${output}    ${splitter}    ${index}
    ${output}=    Split Value from String    ${output}    }
    ${string}=    Get From List    ${output}    ${index}
    ${string}=    Split Value from String    ${string}    ${splitter}
    ${string}=    Get From List    ${string}    1
    RETURN    ${string}

Find Line
    [Documentation]    Take the output of networkdevice:get-reachable, find the line
    ...    with the give IP with the given IP address and return the line
    [Arguments]    ${device_ip}
    ${output}=    Issue Command On Karaf Console    networkdevice:get-reachable
    ${output}=    Split To Lines    ${output}
    ${length}=    Get Length    ${output}
    FOR    ${INDEX}    IN RANGE    0    ${length}
        ${line}=    Get From List    ${output}    ${INDEX}
        ${data}=    Fetch From Right    ${line}    ipAddress=IpAddress{value=
        ${data}=    Split String    ${data}    },
        ${data}=    Get From List    ${data}    0
        IF    '${data}' == '${device_ip}'            BREAK
    END
    RETURN    ${line}

Find Device Id
    [Documentation]    Find the device ID using its IP address
    [Arguments]    ${device_ip}
    ${line}=    Find Line    ${device_ip}
    ${id}=    Split String    ${line}    NetworkDevice{id=SerialNumber{value=
    ${id}=    Get From List    ${id}    1
    ${id}=    Fetch from Left    ${id}    }
    RETURN    ${id}

Find Device Name
    [Documentation]    Find the device's name using its IP address
    [Arguments]    ${device_ip}
    ${line}=    Find Line    ${device_ip}
    ${line}=    Split String    ${line}    ,
    ${line}=    Get From List    ${line}    -2
    ${name}=    Split String    ${line}    friendlyName=
    ${name}=    Get From List    ${name}    1
    RETURN    ${name}

Find Device Location
    [Documentation]    Find the device's location using its IP address
    [Arguments]    ${device_ip}    ${location}
    ${line}=    Find Line    ${device_ip}
    ${line}=    Split String    ${line}    ,
    ${line}=    Get From List    ${line}    3
    ${name}=    Split String    ${line}    location=
    ${name}=    Get From List    ${name}    1
    RETURN    ${location}

Find User State
    [Documentation]    Find the user's state
    [Arguments]    ${output}
    ${output}=    Split Value from String    ${output}    ,
    ${data}=    Get From List    ${output}    4
    ${data}=    Remove Space on String    ${data}
    ${data}=    Split String    ${data}    }
    RETURN    ${data}

Setup Persistence Test App Environment
    [Documentation]    Installing Persistence Related features
    Install a Feature    odl-persistence-all
    Install a Feature    odl-persistence-test-app
    Verify Feature Is Installed    odl-persistence-api
    Verify Feature Is Installed    odl-persistence-jpa-impl
    Verify Feature Is Installed    odl-persistence-test-app

Cleanup Persistence Test Database
    [Documentation]    Clear the database and uninstall Persistence Test App
    Uninstall a Feature    odl-persistence-api
    Uninstall a Feature    odl-persistence-jpa-impl
    Uninstall a Feature    odl-persistence-test-app
    Verify Feature Is Not Installed    odl-persistence-api
    Verify Feature Is Not Installed    odl-persistence-jpa-impl
    Verify Feature Is Not Installed    odl-persistence-test-app
