data_models = [
    'config/ietf-interfaces:interfaces',
    'config/interface-service-bindings:service-bindings',
    'config/itm:transport-zones',
    'config/itm-config:tunnel-monitor-enabled',
    'config/itm-config:tunnel-monitor-interval',
    'config/itm-config:tunnel-monitor-params',
    'config/itm-state:dpn-endpoints',
    'config/itm-state:dpn-teps-state/ |python -m json.tool',
    'config/itm-state:external-tunnel-list',
    'config/itm-state:tunnel-list',
    'config/network-topology:network-topology/topology/ovsdb:1',
    'config/odl-interface-meta:bridge-interface-info',
    'config/odl-interface-meta:interface-child-info',
    'config/odl-itm-meta:bridge-tunnel-info/ |python -m json.tool',
    'config/opendaylight-inventory:nodes',
    'operational/ietf-interfaces:interfaces-state',
    'operational/interface-service-bindings:bound-services-state-list',
    'operational/itm-config:tunnel-monitor-enabled',
    'operational/itm-config:tunnel-monitor-interval',
    'operational/itm-config:tunnel-monitor-params',
    'operational/itm-state:tunnels_state',
    'operational/network-topology:network-topology/topology/ovsdb:1',
    'operational/odl-interface-meta:bridge-ref-info',
    'operational/odl-interface-meta:dpn-to-interface-list',
    'operational/odl-interface-meta:if-indexes-interface-map',
    'operational/odl-itm-meta:dpn-to-interface-list/ |python -m json.tool',
    'operational/odl-itm-meta:if-indexes-tunnel-map/ |python -m json.tool',
    'operational/odl-itm-meta:ovs-bridge-ref-info/ |python -m json.tool',
    'operational/opendaylight-inventory:nodes',
]

idmanager_data_models = [
    'config/id-manager:id-pools/',
    'operational/lock-manager:locks/',
]
