bfd_data_models = [
        'config/itm-config:tunnel-monitor-enabled',
        'config/itm-config:tunnel-monitor-interval',
        'config/itm-state:dpn-endpoints',
        'config/itm-state:external-tunnel-list',
        'config/itm:transport-zones',
        'config/network-topology:network-topology',
        'config/opendaylight-inventory:nodes',
        'operational/ietf-interfaces:interfaces',
        'operational/ietf-interfaces:interfaces-state',
        'operational/itm-config:tunnel-monitor-enabled',
        'operational/itm-config:tunnel-monitor-interval',
        'operational/itm-state:tunnels_state',
        'operational/network-topology:network-topology',
        'operational/odl-interface-meta:bridge-ref-info',
]
