*** Variables ***
# DIDM suite variables
${DEVICE_IP}      ${TOOLS_SYSTEM_IP}
${TOOLS_SYSTEM_IP}        ${DEVICE_IP}
${DEVICE_USER}    ${TOOLS_SYSTEM_USER}
${TOOLS_SYSTEM_USER}    ${DEVICE_USER}
${DEVICE_PASSWORD}    ${TOOLS_SYSTEM_PASSWORD}
${TOOLS_SYSTEM_PASSWORD}    ${DEVICE_PASSWORD}
${TOOLS_SYSTEM_PROMPT}    ${TOOLS_SYSTEM_PROMPT}
${DEVICE_TYPE}    mininet
${DEVICE_DESCRIPTION}    None
${DEVICE_HW_INFO}    Open vSwitch
${DEVICE_SW_INFO}    2.0.0
${DEVICE_MANUFACTURE}    Nicira, Inc.
${DEVICE_SERIAL_NUMBER}    None
