CONFIG_API = '/restconf/config'
OS_COMPUTE_1_IP = '192.168.122.181' #Compute Node 1 IP
OS_COMPUTE_2_IP = '192.168.122.151'  #Compute node 2 + ODL IP
OS_CONTROL_NODE_IP = '192.168.122.186'
OS_USER = 'mininet'
DEVSTACK_SYSTEM_PASSWORD = 'mininet'
#OS_USER = 'root'
DEVSTACK_DEPLOY_PATH = '/home/stack/devstack/'
# ODL system variables
ODL_SYSTEM_IP = '192.168.122.171'  # Override if ODL is not running locally to pybot
ODL_SYSTEM_1_IP = '192.168.122.171'
USER_HOME = '/root/'
DELAY_AFTER_VM_CREATION = 30
DCGW_SYSTEM_IP = '192.168.122.59'
VAR_BASE = '/home/mininet/SF218/test/csit/variables/bgpfunctional'
RESTCONFPORT = 8181
BGP_CONFIG_CMD = "odl:configure-bgp -op start-bgp-server --as-num 100 --router-id " + ODL_SYSTEM_IP
BGP_CONFIG_ADD_NEIGHBOR_CMD = "odl:configure-bgp -op add-neighbor --ip " + DCGW_SYSTEM_IP + " --as-num 100"
BGP_NEIGHBOR_DELETE_CMD = "odl:configure-bgp -op delete-neighbor --ip " + DCGW_SYSTEM_IP
BGP_SHOW = "odl:display-bgp-config"
