apiVersion: v1
kind: Pod
metadata:
  name: busybox4
  labels:
    app: busybox4
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  nodeSelector:
     disktype: ssl


