apiVersion: v1
kind: Pod
metadata:
  name: busybox3
  labels:
    app: busybox3
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  nodeSelector:
     disktype: ssd

