coe-master:
  hosts:
    master_ip:
  vars:
    external_interface: ~
    overlay_ip: master_ip
    external_ip: ~
    subnet: 10.11.1.0/24
    gateway: 10.11.1.1
    manager_ip: odl_ip
    manager_port: mport
    controller_ip: odl_ip
    controller_port: cport
    go_version: \1.10.2\
    conf_path: filepath
    k8s_advertise_address: master_ip
    watcher_path: yamlpath

coe-minion1:
  hosts:
    minion1_ip:
  vars:
    external_interface: enp0s9
    overlay_ip: minion1_ip
    external_ip: 192.168.50.12
    subnet: 10.11.2.0/24
    gateway: 10.11.2.1
    manager_ip: odl_ip
    manager_port: mport
    controller_ip: odl_ip
    controller_port: cport
    go_version: \1.10.2\
    conf_path: filepath

coe-minion2:
  hosts:
    minion2_ip:
  vars:
    external_interface: enp0s9
    overlay_ip: minion2_ip
    external_ip: 192.168.50.13
    subnet: 10.11.3.0/24
    gateway: 10.11.3.1
    manager_ip: odl_ip
    manager_port: mport
    controller_ip: odl_ip
    controller_port: cport
    go_version: \1.10.2\
    conf_path: filepath
